---
sass:
  sass_dir: css
  style: expanded
nav:
- title: Welcome
  href: "/jekyll-starter-theme-v2/"
- title: Page Two
  href: "/jekyll-starter-theme-v2/two.html"
- title: Page Three
  href: "/jekyll-starter-theme-v2/three.html"
- title: Questions? Comments?
  href: http://groups.google.com/group/wwwmake
- title: About
  href: https://github.com/henrythemes/jekyll-starter-theme-v2
url: http://wwbbxm3nes6gma.preview.forestry.io
path: "/jekyll-starter-theme-v2"
subtitle: Another Static Site Quick Starter Theme
title: Jekyll Starter Theme V2
kramdown:
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: '1'
port: 4000
exclude:
- README.md
- vendor
collections:
  posts:
    output: true
    permalink: "/:categories/:year/:month/:day/:title:output_ext"
